# docker-compose for nfs-client
#
version: "2.4"
services:

  nfs-client:
    privileged: true
    image: phlax/nfs-client
    networks:
    - nfs
    environment:
      NFS_0: nfs4 nfs-server /directory1
      NFS_1: nfs4 nfs-server /directory2 nfsvers=4,ro

  nfs-server:
    privileged: true
    image: phlax/nfs-server
    networks:
    - nfs
    environment:
    - NFS_EXPORT_0=/export *(rw,fsid=0,no_subtree_check,sync,no_root_squash)
    - NFS_EXPORT_1=/export/directory1 *(rw,no_subtree_check,no_root_squash)
    - NFS_EXPORT_2=/export/directory2 *(ro,no_subtree_check,no_root_squash)
    volumes:
    - ${PWD}/export:/export

networks:
  nfs:
