# https://travis-ci.org/#!/phlax/nfs-client
dist: bionic
language: python

before_install:
  - make images
  - make proxy-example
  - make pysh
  - sudo modprobe nfs
  - sudo modprobe nfsd

install:

  - mkdir -p ./export/directory1
  - mkdir -p ./export/directory2

  # set the environment
  - echo "COMPOSE_FILE=./example/docker-compose.yml" > ./.env

script:
  - docker-compose up -d nfs-server
  - docker-compose logs nfs-server

  - pysh ./tests/mount
  - pysh ./tests/proxy

before_deploy:
  - echo $DOCKER_PASSWORD | docker login -u phlax --password-stdin

deploy:
  provider: script
  script: make hub-images
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master)$
